// <auto-generated />
using System;
using Lab.Aml.DataPersistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab.Aml.DatabaseDesign.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240903211143_SeedOptionalData")]
    partial class SeedOptionalData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab.Aml.DataPersistence.Entities.Customer", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Birthdate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "ul. Kwiatowa 5, 00-001 Warszawa",
                            Birthdate = new DateOnly(1990, 6, 15),
                            Name = "Anna",
                            Surname = "Kowalska"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "ul. Słoneczna 12, 31-234 Kraków",
                            Birthdate = new DateOnly(1985, 3, 22),
                            Name = "Jan",
                            Surname = "Nowak"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "ul. Ogrodowa 8, 40-600 Katowice",
                            Birthdate = new DateOnly(1995, 10, 11),
                            Name = "Katarzyna",
                            Surname = "Zielińska"
                        });
                });

            modelBuilder.Entity("Lab.Aml.DataPersistence.Entities.Limit", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<decimal?>("Amount")
                        .IsRequired()
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("Count")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Range")
                        .IsRequired()
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Limits");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 11000m,
                            Count = 11,
                            CreationDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = 1,
                            Range = new TimeSpan(0, 0, 5, 0, 0)
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 12000m,
                            Count = 12,
                            CreationDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            Range = new TimeSpan(0, 0, 5, 0, 0)
                        },
                        new
                        {
                            Id = 3L,
                            Amount = 13000m,
                            Count = 13,
                            CreationDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = 3,
                            Range = new TimeSpan(0, 0, 5, 0, 0)
                        },
                        new
                        {
                            Id = 4L,
                            Amount = 21000m,
                            Count = 21,
                            CreationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = 1,
                            Range = new TimeSpan(0, 0, 5, 0, 0)
                        },
                        new
                        {
                            Id = 5L,
                            Amount = 22000m,
                            Count = 22,
                            CreationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            Range = new TimeSpan(0, 0, 6, 0, 0)
                        },
                        new
                        {
                            Id = 6L,
                            Amount = 23000m,
                            Count = 23,
                            CreationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = 3,
                            Range = new TimeSpan(0, 0, 7, 0, 0)
                        });
                });

            modelBuilder.Entity("Lab.Aml.DataPersistence.Entities.Transaction", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<decimal?>("Amount")
                        .IsRequired()
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("CreationDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsSuspicious")
                        .HasColumnType("bit");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 150.00m,
                            CreationDate = new DateTime(2023, 1, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Currency = 3,
                            CustomerId = 1L,
                            Description = "Initial deposit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 75.50m,
                            CreationDate = new DateTime(2023, 1, 2, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Currency = 3,
                            CustomerId = 1L,
                            Description = "ATM withdrawal",
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 3L,
                            Amount = 300.00m,
                            CreationDate = new DateTime(2023, 1, 3, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 2L,
                            Description = "Online transfer",
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 4L,
                            Amount = 1000.00m,
                            CreationDate = new DateTime(2023, 1, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Currency = 1,
                            CustomerId = 3L,
                            Description = "Salary deposit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 5L,
                            Amount = 50.00m,
                            CreationDate = new DateTime(2023, 1, 5, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            Currency = 3,
                            CustomerId = 1L,
                            Description = "Grocery payment",
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 6L,
                            Amount = 120.00m,
                            CreationDate = new DateTime(2023, 1, 6, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            Currency = 3,
                            CustomerId = 2L,
                            Description = "Gift deposit",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 7L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 2, 15, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 8L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 3, 15, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 9L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 10L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 11L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 12L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 13L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 14L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 15L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 16L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 31, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 17L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 32, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 18L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 33, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 19L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 34, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 20L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 35, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 21L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 36, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 22L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 37, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 23L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 38, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 24L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 39, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 25L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 40, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 26L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 41, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 27L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 42, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 28L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 43, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 29L,
                            Amount = 450.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 44, 0, 0, DateTimeKind.Unspecified),
                            Currency = 3,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 30L,
                            Amount = 45.00m,
                            CreationDate = new DateTime(2023, 4, 15, 23, 45, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 31L,
                            Amount = 100.00m,
                            CreationDate = new DateTime(2024, 1, 1, 1, 1, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 3L,
                            Description = "Online shopping",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 32L,
                            Amount = 100000.00m,
                            CreationDate = new DateTime(2024, 2, 1, 1, 1, 0, 0, DateTimeKind.Unspecified),
                            Currency = 2,
                            CustomerId = 1L,
                            Description = "Online shopping",
                            TransactionType = 1
                        });
                });

            modelBuilder.Entity("Lab.Aml.DataPersistence.Entities.Transaction", b =>
                {
                    b.HasOne("Lab.Aml.DataPersistence.Entities.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Lab.Aml.DataPersistence.Entities.Customer", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
